---
name: Build and Push Webserver to S3
on:
  push:
    paths:
      - '.github/**'
    branches:
    - 'main'
    
jobs:
  build-and-push:
    name: Build and Push to ECR
    runs-on: macos-13
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Resolve dependencies
      uses: action/checkout@v3
      with:
        repository: 'ccgus/fmdb'
        ref: '2.7.7'
        path: 'FMDB'
