---
name: Build and Push Webserver to S3
on:
  push:
    paths:
      - '.github/**'
    branches:
    - 'main'
    
jobs:
  build-and-push:
    name: Build and Push to ECR
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Resolve dependencies
      uses: action/checkout@v2
      with:
        repository: github.com:ccgus/fmdb.git
        ref: 2.7.7
        path: FMDB
