---
name: Build and Push Webserver to S3
on:
  push:
    paths:
      - '.github/**'
    branches:
    - 'main'
    
jobs:
  build-and-push:
    name: Build and Push to ECR
    runs-on: macos-13
    steps:
    - name: Checkout
      uses: actions/checkout@v2
  
