---
name: Build and Push Webserver to S3
on:
  push:
    paths:
      - '.github/**'
    branches:
    - 'main'
    
jobs:
  build-and-push:
    name: Build and Push to ECR
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Clone remote private repo
      uses: actions/checkout@v3
      with:
        repository: networkthor/vmware-workpro16
        ref: main
        path: license
        ssh-key: ${{ secrets.SSH_PRIVATE }}

    - name: Resolve dependencies
      uses: actions/checkout@v3
      with:
        repository: ccgus/fmdb
        ref: 2.7.7
        path: FMDB
    
    - uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_COLOR: ${{ job.status }}
